### ISSUE TITLE
Recreate Table 3 from Hector v3.2.0 Manuscript

### ISSUE THREAD

**Issue by ptrscll** [kdorheim/2024.SULI.practice#16]
Write script to recreate Table 3 from the Hector v3.2.0 manuscript. Before actually writing code, write out in Google Docs pseudocode detailing the following information for each metric:

- What Hector runs are needed to obtain the value and if I need an input file from Kalyn
- Any functions needed and a brief description of them and their arguments/return values/etc.

**Comment by ptrscll** [comment]
Link to Google Doc with my pseudocode/plans:
https://docs.google.com/document/d/1-cmwgvTeBRXxLQTQpUL3oTMGibywyDXJp0zlKbNaOVE/edit?usp=sharing

The doc includes what files I need from Kalyn and several questions for Kalyn.

**Comment by kdorheim** [comment]
[idealized_inputs.zip](https://github.com/user-attachments/files/15593946/idealized_inputs.zip)
Here are the inputs for the idealized runs! Please let me know if you have issues/questions

**Comment by kdorheim** [comment]
To save you some time here is a list of all the RF agents in Hector 
```
# List of all the forcing agents in Hector 
all_rf <- c(RF_ALBEDO(), RF_CO2(), RF_H2O_STRAT(), RF_O3_TROP(), RF_BC(), RF_OC(), RF_NH3(),
            RF_SO2(), RF_ACI(), RF_VOL(), RF_MISC(), RF_CH4()
            , RF_CF4(), RF_C2F6(), RF_HFC23(), RF_HFC32(), RF_HFC4310(), RF_HFC125(), RF_HFC134A(), RF_HFC143A(), 
            RF_HFC227EA(), RF_HFC245FA(), RF_SF6(), RF_CFC11(), RF_CFC12(), RF_CFC113(), RF_CFC114(), RF_CFC115(), 
            RF_CCL4(), RF_CH3CCL3(), RF_HCFC22(), RF_HCFC141B(), RF_HCFC142B(), RF_HALON1211(), RF_HALON1301(), 
            RF_HALON2402(), RF_CH3CL(), RF_CH3BR())
```

**Comment by kdorheim** [comment]
@ptrscll I think your pseudo code document looks great! but I have a few questions/things for you to consider 

- Where do you want to write this? (in a R or Rmd file) 
- How/where do you plan on saving results? This may change depending on how you decide to write this
- It looks like you will be doing lots of hector runs for lots of different scenarios, would it make sense to write a my_hector_run function?

**Comment by kdorheim** [comment]
I would also like you to prioritize which values you start working on. I'd like you to open a PR after you finish the first tier of values 

- [x] Tier 1: Future Warming (GSAT, °C relative to 1995-2014)
- [x] Tier 2: Historical Warming and Effective Radiative Forcing 
- [ ] Tier 3: Key Metrics

**Comment by kdorheim** [comment]
## How to Calculate Ocean Heat Content Change 
```
ocean_area <- 5100656e8 * (1 - 0.29) # The total area of the ocean 
unit_conversion <- 3.155693e-14      # Watts to ZJ 
```
`HEAT_FLUX()` returns the per year value so to get at the to calculate ocean heat content change you will need to take the sum of `HEAT_FLUX()` value 

```
sum(HEAT_FLUX()) * ocean_area * unit_conversion
```

**Comment by ptrscll** [comment]
> @ptrscll I think your pseudo code document looks great! but I have a few questions/things for you to consider
> 
> * Where do you want to write this? (in a R or Rmd file)

Right now, I'm thinking it would be more straightforward to just write everything in an R file.
> * How/where do you plan on saving results? This may change depending on how you decide to write this

I'm currently planning on saving all my results to a .txt file.
> * It looks like you will be doing lots of hector runs for lots of different scenarios, would it make sense to write a my_hector_run function?

Yeah, that definitely seems like a good call.

**Comment by ptrscll** [comment]
I was able to get my code for all the historical metrics to work properly but I have a couple of questions about the key metrics runs:

- Is ECS rounded to the nearest integer? Right now I'm getting an ECS of 2.81 degrees, but I'm not sure if that's right.
- What start/end year should I be using for finding the change in temperature and total emissions for TCRE?
- I noticed that for the TCR idealized run, carbon dioxide concentrations don't start changing until 1800. Should I start the values for my data frame at 1745, where the first CO2 data is given, or at 1800 when the concentrations start actually increasing?

**Comment by kdorheim** [comment]
* @ptrscll what does your plot of the x2 CO2 run look like? 
* TCRE you can start in 1750, since this is a slope the start and stop date don't matter too much. The one exception is there should be no negative emissions! (this shouldn't be an issue based on the scenario we've selected to use)
* good catch, yes start at 1800!

**Comment by ptrscll** [comment]
This is what the temperature plot of my x2 CO2 run looks like:

![2xCO2_plot](https://github.com/kdorheim/2024.SULI.practice/assets/103226047/cf5a9871-ffd2-4b44-b8ea-49079b1ff16b)
