### ISSUE TITLE
Intro to runing Hector

### ISSUE THREAD

**Issue by kdorheim** [kdorheim/2024.SULI.practice#2]
@ptrscll please complete the [1A.intro-hector-runs.R](https://github.com/kdorheim/2024.SULI.practice/blob/main/01/1A.intro-hector-runs.R) script and open a PR with the completed script this will give us a chance to practice the PR process

You are going to need to 
- clone the repo
- make a branch 
- complete the 1A.intro-hector-runs.R, where you will learn to set up and run Hector & practice visualizing data (please make sure to comment your code)
- commit your changes to your branch 
-  add your plots to this GitHub issue & open a PR

**Comment by ptrscll** [comment]
## 4A Plots:
![CO2_concentration_time](https://github.com/kdorheim/2024.SULI.practice/assets/103226047/3e316827-d687-48c3-966c-5d0897fd19ed)
![global_tas_time](https://github.com/kdorheim/2024.SULI.practice/assets/103226047/fca8c4a2-02a6-4877-9b5d-8b0a1fa64630)
![gmst_time](https://github.com/kdorheim/2024.SULI.practice/assets/103226047/6b409564-0f66-4264-ad4c-996517a02bae)

## 4B Plot:
![combined_plot](https://github.com/kdorheim/2024.SULI.practice/assets/103226047/cdf7c98d-db01-4f0e-aa43-63c7f949abf3)

## 4C Plot:
![T_comparison](https://github.com/kdorheim/2024.SULI.practice/assets/103226047/06a79787-1b5e-4a82-b772-7a6b25a6e773)
